const data = {
  products: [
    {
      id: "1",
      name: "cologne 1",
      category: "men's cologne",
      image: "./images/DiorSauvage.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "2",
      name: "cologne 1",
      category: "men's cologne",
      image: "./images/DiorSauvage.jpg",
      price: 120,
      brand: "Dior",
      rating: 4.5,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "3",
      name: "cologne 1",
      category: "men's cologne",
      image: "./images/DiorSauvage.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "4",
      name: "cologne 1",
      category: "men's cologne",
      image: "./images/DiorSauvage.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "5",
      name: "cologne 1",
      category: "men's cologne",
      image: "./images/DiorSauvage.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
  ],
};

export default data;
