const data = {
  products: [
    {
      id: "1",
      name: "Sauvage",
      category: "men's cologne",
      image: "/images/DiorSauvage.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "2",
      name: "Gio",
      category: "men's cologne",
      image: "/images/Gio.jpg",
      price: 120,
      brand: "Dior",
      rating: 4.5,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "3",
      name: "tomford",
      category: "men's cologne",
      image: "/images/tomford.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "4",
      name: "cologne 1",
      category: "men's cologne",
      image: "/images/versace.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
    {
      id: "5",
      name: "infinity",
      category: "men's cologne",
      image: "/images/infinity.jpg",
      price: 120,
      brand: "Dior",
      rating: 4,
      numReviews: 7,
      description: "A very good fragrance",
    },
  ],
};

export default data;
